KhronosGroup/OpenCL-SDK

samples/core/enumopencl/main.cpp
Fix issue #17 by setting `deviceProfile = NULL;` in the code block with the other char arrays.
=> Fix enumopencl for issue #17

samples/CMakeLists.txt, samples/core/copybuffer/CMakeLists.txt, samples/core/copybufferkernel/CMakeLists.txt, samples/core/enumopencl/CMakeLists.txt
Fixes #22.
I ended up keeping `TEST` since I've found it useful, but I don't remind removing it if desired.
(It doesn't do anythign right now anyhow, since the OpenCL SDK currently doesn't enable testing.)
=> enhance the CMake function to add samples

.github/workflows/presubmit.yml, ruby/README.md, ruby/copybuffer/copybuffer.rb, ruby/copybufferkernel/copybufferkernel.rb, ruby/enumopencl/enumopencl.rb, ruby/rakefile
This pull request adds Ruby samples reproducing the C/C++ samples already present in the SDK.
It also adds CI on Ubuntu and MacOS. If an OpenCL platform could be installed on windows, we could test it there as the bindings have been reported to work on windows as well.
=> Add OpenCL ruby samples

.github/workflows/release.yml, CMakeLists.txt, docs/RELEASE.md
This PR holds automation for source and binary releases of the SDK whenever a version tag is applied. It only creates a draft release which then has to be manually verified and published. (The UI is fairly straightforward) A draft release which runs after adding a version tag look like [this](https://github.com/StreamHPC/OpenCL-SDK/releases/tag/untagged-1c69145d6331af93ae5b).
Currently only Windows binary releases are done, because that is the platform which necessitates this the most, but later iterations can expand on that. (I would call on people actually shipping Linux releases, not just libraries to tune in on what is the optimal set of release build flags on Linux.) Submodule source files are included in the source tarballs.
_(Unfortunately I can't remove the automatic source …
=> Initial release scripts

.github/workflows/presubmit.yml, lib/CMakeLists.txt, test/cmake/pkgconfig/platformenum/CMakeLists.txt, test/cmake/pkgconfig/useutil/CMakeLists.txt, test/cmake/useutil.c, test/cmake/useutil.cpp
On Windows, Debug and Release C++ libraries aren't link compatible. If the name of a library on disk is the same for both Debug and Release builds, they can't be installed side-by-side and makes it much harder to consume them for development purposes where both versions would be needed. This PR addresses that by changing the name of the utility libraries on disk for Debug builds, so they can coexist with Release artifacts.
_(Note that CI doesn't test it yet, because the OpenCL-SDK's CI is still fairly rudimentary. This feature still requires manual testing.)_
=> Fix UtilsCpp debug install

samples/core/enumopencl/CMakeLists.txt, samples/core/enumopencl/main.c, samples/core/enumopencl/main.cpp
This change switches the existing enumopencl sample to use pure C, compilable with a C compiler (no C++).
It also adds an equivalent C++ sample that makes extensive use of the OpenCL C++ bindings.
The output from both samples is identical.
=> add pure C and C++ versions of the enumopencl sample

CMakeLists.txt
I'm not sure if I'm allowed to bump submodules, but it would be useful for the _blurcpp_ example I want to commit.
It updates:
1. OpenCL-CLHPP
2. OpenCL-Headers
3. OpenCL-ICD-Loader
to the latest main.
=> update project version and bump submodules

README.md
"Instroduces" -> "Introduces", "it's" -> "its"; also added a couple of commas and colons
=> Fix typos + light copyediting in ReadMe

.github/workflows/presubmit.yml
Add installing of libxcursor-dev which newer SFML versions require from the system.
=> Fix Vcpkg build failures in CI

samples/core/multi-device/CMakeLists.txt, samples/core/multi-device/README.md, samples/core/multi-device/convolution.cl, samples/core/multi-device/main.c, samples/core/multi-device/main.cpp
This PR adds the C/C++ samples showcasing a multi-device convolution computation that makes use of sub-devices and sub-buffers.
~Note: only the last commit is relevant for the PR, all the other commits are from the [StreamHPC:release-cd](https://github.com/StreamHPC/OpenCL-SDK/tree/release-cd) branch. After https://github.com/KhronosGroup/OpenCL-SDK/pull/88 is merged, this should be trivial to rebase/merge.~
=> Implemented multi-device sample

include/api/CL, include/cpp/CL, include/utils/CL
These symlinks cause issues when the SDK is deployed on some systems.
Fixes #82
=> remove unused symlinks

lib/src/Utils/File.c
fopen_s, (and the defined macro), return 0 on success, but the if statement is expecting a non-zero value on success.
This causes cl_util_write_binaries to fail, even though it is successfully opening a file.
Can be tested very easily by building and running the "binaries" sample program.
=> Fix Backwards fopen_s Check

.github/workflows/presubmit.yml, CMakeLists.txt, samples/core/callback/CMakeLists.txt
Update project version and submodules for an upcoming release.
=> update project version and submodules - April 2024

lib/include/CL/Utils/Error.hpp
`throw()` was deprecated in C++11 and removed in C++17. `noexcept` is the appropriate replacement.
=> throw() -> noexcept

cmake/Dependencies/whereami/whereami.cmake
When adding OpenCL-SDK  via CPMAddPackage (cmake 3.22.1) as such:
```
CPMAddPackage(
NAME OpenCL_SDK
GIT_TAG v2023.12.14
GITHUB_REPOSITORY "KhronosGroup/OpenCL-SDK"
OPTIONS
"BUILD_TESTING OFF"
"BUILD_TESTS OFF"
"BUILD_DOCS OFF"
"OPENCL_SDK_BUILD_SAMPLES OFF"
"OPENCL_SDK_TEST_SAMPLES OFF"
"OPENCL_SDK_BUILD_OPENGL_SAMPLES OFF"
)
```
the following is issued:
```
CMake Error at build/_deps/opencl_sdk-src/lib/CMakeLists.txt:23 (add_libr
ary):
Cannot find source file:
##############/proj/build/_deps/opencl_sdk-build/_d
eps/whereami-external-src/src/whereami.c
Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
.h
.hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .is
pc
CMake Error in build/_deps/opencl_sdk-src/lib/CMakeLists.txt:
Imported target "whereami" …
```
=> Fix whereami dependency target

README.md
found while responding to #121 
The paths described in the README do not exist.  This PR fixes them.
=> update the paths to OpenCL include files and libraries in the README

lib/CMakeLists.txt, test/cmake/pkgconfig/useutil/CMakeLists.txt
The utility libraries accidentally had whereami linkage in their install targets which imposed an unnecessary requirement on users of the utility library. The tests worked around this issue instead of fixing it.
=> Fix install rule for utility libraries

.github/workflows/presubmit.yml, README.md, cmake/Dependencies/SFML/SFML.cmake, vcpkg.json
All Vcpkg CI elements started failing recently, which is fixed by this PR. The core of the issue was that SFML, a dependency of the graphical samples built in CI have released a new major version, SFML3, which is incompatible with SFML2. It has slightly different CMake-side support, as well as slightly different interfaces. The fix involves pinning the version of SFML fetched from CMake, which can only be done via a manifest file; it's not possible via the CLI.
- There are two commits in this PR. The first strictly deals with introducing the manifest file for Vcpkg and updating autofetching to the latest 2.x version available.
- Caching Vcpkg installs got removed for the time being. Partly because it needs to be done differently (given how it's not a separate CLI invocation now, but part …
=> Sfml ver fix

.github/workflows/presubmit.yml, CMakeLists.txt, cmake/Dependencies.cmake, cmake/Dependencies/Vulkan/Vulkan.cmake, samples/CMakeLists.txt, samples/extensions/khr/CMakeLists.txt, samples/extensions/khr/externalmemory/CMakeLists.txt, samples/extensions/khr/externalmemory/README.md, samples/extensions/khr/externalmemory/external_saxpy.cl, samples/extensions/khr/externalmemory/main.c, samples/extensions/khr/externalmemory/main.cpp, samples/extensions/khr/externalmemory/vulkan_utils.h, samples/extensions/khr/externalmemory/vulkan_utils.hpp
**NOTE**: this PR includes all commits from branch [StreamHPC:release-cd](https://github.com/StreamHPC/OpenCL-SDK/tree/release-cd). This is required, because the implemented sample requires additional updates to the CI scripts to pull its new dependencies. After #88 is merged, this should be trivial to rebase/merge. Only the last commit is relevant for the sample, all other commits are from the `release-cd` branch.
- Implemented sample showcasing the interop of OpenCL and Vulkan, using external memory,
- for details, please visit the newly added README file.
=> Implemented external memory sample

.github/workflows/presubmit.yml, CMakeLists.txt, README.md
The current README build instructions are more complicated than they need to be.  Much simpler build instructions can be used in most cases.  So, document the simpler build instructions, instead.
Additionally:
* Document the OpenCL SDK CMake variables that may be used to control the build.
* Disable samples that require Vulkan by default, to reduce build dependencies.  Note that OpenGL samples were already disabled by default.
* Add CI configs to test the simple README build instructions on Windows, Linux, and Mac.
see: #70
=> updates README build instructions

samples/core/binaries/main.c, samples/core/blur/main.c, samples/core/multi-device/main.c, samples/core/reduce/main.c, samples/core/saxpy/main.c, samples/extensions/khr/externalmemory/main.c, samples/extensions/khr/externalmemory/main.cpp
Fix memory leaks and cleanup logic in the following sample programs:
- samples/core/binaries
- samples/core/blur
- samples/core/reduce
- samples/core/saxpy
- samples/core/multi-device
- samples/extensions/khr/externalmemory
Also fix minor logic and error-handling inconsistencies such as:
- Ensuring proper release of cl_event objects
- Correct ordering of Vulkan cleanup calls
- Improved version string checks and CLI option allocation
=> Fix samples memory leak and cleanup issues
